#!/usr/bin/env bash
# This script configures container so that Nginx is running as the nginx user

chmod 644 /etc/nginx/nginx.conf
sed -i "25i \\\tlisten 8080;" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
