#!/usr/bin/env bash
# This script configures container so that Nginx is running as the nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "25i \\\tlisten 8080;" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
# pkill apache2
sudo -u nginx service nginx start
